name: Build Kivy Android APK

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          sudo apt update
          # Correction des dépendances du système (libtinfo-dev)
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev build-essential libtinfo-dev
          # CORRECTION APPLIQUÉE : INSTALLATION EXPLICITE DE CYTHON
          pip install buildozer cython
      
      - name: Run Buildozer
        # Cette commande démarre la compilation de l'APK
        run: buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MonCalculatriceAPK
          path: bin/*.apk
