name: Build Kivy Android APK

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev build-essential libtinfo-dev
          # CORRECTION FINALE : Forcer la version 1.4.0
          pip install buildozer==1.4.0 cython
      
      # L'étape de licence est conservée pour garantir l'acceptation
      - name: Initialisation et acceptation des licences Android
        run: yes | buildozer android update
      
      - name: Run Buildozer
        run: buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MonCalculatriceAPK
          path: bin/*.apk
